const ROBOTS_ACTION_TYPES = {
    CHANGE_SEARCHFIELD : 'CHANGE_SEARCHFIELD',

    REQUEST_ROBOTS_START : 'REQUEST_ROBOTS_START',
    REQUEST_ROBOTS_SUCCESS : 'REQUEST_ROBOTS_SUCCESS',
    REQUEST_ROBOTS_FAILED : 'REQUEST_ROBOTS_FAILED',
};

export default ROBOTS_ACTION_TYPES;

